config/routes.rb
Rails.application.routes.draw do
  root 'ideas#index'

  put '/ideas/:id/quality', to: 'ideas#update_quality'

  resources :ideas, only: [:create, :edit, :update, :destroy]
end

app/models/idea.rb
class Idea < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @idea  = Idea.new
    @ideas = Idea.order(created_at: :desc)
  end

  def create
    idea = Idea.create(idea_params)

    render partial: "ideas/idea", locals: {idea: idea}
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    idea = Idea.find(params[:id])
    idea.update_attributes(idea_params)
    redirect_to root_path
  end

  def update_quality
    idea = Idea.find(params[:id])
    idea.update_attributes(quality: params[:quality])

    render text: "changed!"
  end

  def destroy
    idea = Idea.find(params[:id])
    idea.destroy

    render text: "buuuuleeted"
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_idea.html.erb
<li class="idea" id="<%= idea.id %>">
  <h1 class="title"><%= idea.title %></h1>
  <h2 class="body"><%= idea.body %></h2>
  <h4 class="quality"><%= idea.quality %></h4>
  <button class="upvote">upvote</button> - <button class="downvote">downvote</button>
  <br>
  <br>
  <%= link_to "EDIT", edit_idea_path(idea) %> ---
  <button class="delete-button">delete</button>
  <hr>
</li>

app/views/ideas/edit.html.erb
<%= form_for @idea, html: {id: "idea-form" } do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, value: @idea.title, id: "title-input" %>

  <%= f.label :body %>
  <%= f.text_field :body, value: @idea.body, id: "body-input" %>

  <%= f.submit id: "idea-create-button" %>
<% end %>

app/views/ideas/index.html.erb
<h1>MYDEAS</h1>

<hr>

<%= form_for @idea, html: {id: "idea-form" } do |f| %>
  Add an Idea -->
  <%= f.label :title %>
  <%= f.text_field :title, id: "title-input" %>

  <%= f.label :body %>
  <%= f.text_field :body, id: "body-input" %>

  <%= f.submit id: "idea-create-button" %>
<% end %>

<hr>

<form>
  Filter Ideas:
  <input type="text" id="idea-filter">
</form>
<hr>

<ul id="ideas-list">
  <% @ideas.each do |idea| %>
    <%= render partial: "ideas/idea", locals: {idea: idea} %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaBox20</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>